import { article } from "./guide.ts";

export const detailedGuide = [
  article(
    "hr-charts",
    "hr",
    "HR essentials",
    "Read HR charts or focus on one employee",
    "Use a clear selection before comparing people, hours or outstanding work.",
    "/staff",
    "dashboard chart pie graph filter employee department location recruitment document expiry onboarding",
    [
      "Open Dashboard in your HR role and review the organisation summary.",
      "Use employee search to focus on one person when you need their information rather than company totals.",
      "Set the available date, department and location filters for the chart you are reading.",
      "Read the chart labels: working hours, leave, recruitment, joining progress and document expiry measure different things.",
      "Open the related employee record or module when you need to investigate or take action.",
    ],
    "Charts summarise the selected information. Some summaries, such as current document expiry, have their own stated time window rather than the attendance date range.",
    [
      "Compare the same period and filters before reporting a discrepancy. A historical completed-days chart does not include today’s running hours.",
      "No data and failed loading are different. Use Retry for a loading error; do not enter a fake record to fill an empty chart.",
    ],
    "employee:view_all",
  ),
  article(
    "hr-attendance-import",
    "hr",
    "Time & leave",
    "Import attendance or add a confirmed manual record",
    "Use confirmed information when records need to be entered by HR.",
    "/staff/attendance",
    "attendance import spreadsheet csv manual record upload confirmed clock in out break location",
    [
      "Open Attendance & Visits → Import & Manual Entry.",
      "For a spreadsheet import, save the sheet in the comma-separated format requested on the page. Include Employee ID, Number or Email, plus Date; optional columns include Clock In, Clock Out, Break Minutes and Location.",
      "Choose the file and review the valid rows and every reported error. Correct errors before choosing Import Validated Rows.",
      "For a single confirmed record, choose New Manual Record. Select the employee and enter the actual date, arrival, departure and break details requested.",
      "Save, then check the daily attendance view for that employee and date.",
    ],
    "Imported and manually entered records should reflect confirmed work, not estimated times used to remove an exception.",
    [
      "Check for an existing record first. Do not repeat an import just because the page is slow.",
      "Read and replace any suggested times in the form with the real times. A default time is not evidence of attendance.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-attendance-exceptions",
    "hr",
    "Time & leave",
    "Resolve an attendance exception case",
    "Keep an unresolved official-duty attendance issue visible until someone checks it.",
    "/staff/attendance",
    "exception case investigating resolve assign missing office origin clock in site visit",
    [
      "Open Attendance & Visits and choose the exception cases section.",
      "Open the case and check the employee, date, destination and missing information.",
      "Assign the responsible person and record investigation notes using the available controls.",
      "Confirm what actually happened and complete any necessary attendance correction through its supported process.",
      "Close the exception only when it has been resolved and the outcome is recorded.",
    ],
    "An office-origin visit that ended without a clock-in can remain as an exception case rather than disappearing after a notification.",
    [
      "Closing the case is not a reason to invent an arrival time. Get confirmation and keep the review record.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-office-zone",
    "hr",
    "HR settings",
    "Set an office area for location-based attendance",
    "Keep office-location checks separate from the fingerprint machine setup.",
    "/staff/attendance",
    "office zone location permission phone accuracy gps radius capture current office",
    [
      "Open Attendance & Visits → Office Setup and choose the correct office location.",
      "When physically at that office, use Capture Current Office if you are setting its permitted area.",
      "Allow the device’s location request and review the captured position and permitted distance before saving.",
      "Review accuracy and working-time choices shown on the page, then test the expected staff experience from that office.",
    ],
    "An office area is used for the applicable location-based attendance checks. The machine connection and employee tracking assignment are separate.",
    [
      "Do not capture your home location as the office. Ask someone on site to carry out the setup.",
      "If a phone cannot locate the employee accurately, check its location permission and use the approved alternative or correction process.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-contacts",
    "hr",
    "Recruitment",
    "Follow up with candidates without duplicate contact",
    "Use the Contact Tracker to see who needs attention and who has already been contacted.",
    "/staff/candidates/contacts",
    "contact queue tracker upcoming recently never do not contact call email next follow up",
    [
      "Open Contact Tracker and choose Action Required, Upcoming, Recently Contacted or Never Contacted.",
      "Open the candidate and read the latest contact outcome before calling or writing.",
      "Record the new contact and its outcome in the candidate’s contact history. Set any next follow-up requested.",
      "Check Do Not Contact before further outreach, and respect the recorded restriction.",
    ],
    "Colleagues can see the updated history and avoid repeating the same approach.",
    [
      "A recent-contact warning means check first, not contact the person again automatically.",
      "Keeping a candidate for future opportunities does not override a Do Not Contact instruction.",
    ],
    "recruitment:view_candidates",
  ),
  article(
    "hr-expiry",
    "hr",
    "Documents & insurance",
    "Follow document renewals before they expire",
    "Review due and overdue documents and keep renewal evidence accurate.",
    "/staff/document-expiry",
    "expiry renewal overdue passport visa permit insurance reminder document dates",
    [
      "Open Document Expiry and use the available employee or document filters.",
      "Check the document type, expiry date and whether the current version is verified.",
      "Ask the responsible person for the renewal and follow up before the deadline.",
      "Upload or replace the document in its original document area, check the new dates and complete the review.",
      "Return to the expiry list to confirm the current record reflects the renewal.",
    ],
    "A reminder does not extend a document’s validity. A newly uploaded draft may still require HR verification.",
    [
      "Do not simply move the expiry date forward without the actual renewed document.",
      "Company registrations are managed in Policies & Documents; employee documents belong to the individual file.",
    ],
    "document:manage_all",
  ),
  article(
    "anniversaries",
    "employee",
    "People & opportunities",
    "Check work anniversaries",
    "See joining anniversaries using the employment dates recorded by HR.",
    "/staff/anniversaries",
    "anniversary joining date years service start date celebration",
    [
      "Open Work Anniversaries from the Employees menu.",
      "Review the employees and dates shown, using any available filters.",
      "If your joining date or years of service look wrong, ask HR to check your confirmed employment start date.",
    ],
    "Anniversaries follow the recorded employment information, not the date you first opened the app.",
    ["Employees cannot correct an HR-controlled joining date by editing their contact profile."],
  ),
];
