import { article } from "./guide.ts";

export const employeeGuide = [
  article(
    "time-away",
    "employee",
    "Attendance",
    "Record time away during work",
    "Record appointments or personal absences after clocking in.",
    "/staff/time-away",
    "hospital appointment personal time away absence manager",
    [
      "Open My Attendance and choose Record / view time away. Choose the date, then Record time away.",
      "Choose yourself, or a member of your team if you are using the Line Manager role. Enter departure and return times and a category. A note is optional; do not include medical details.",
      "Submit for HR review. You can record an earlier date. If times are wrong, cancel the pending record and submit the correct times.",
      "HR approves or rejects the record. Check the result and any instructions in the app notification. A rejected record can be submitted again with corrected details.",
    ],
    "Clock-in/out remains unchanged. Time away is recorded separately and does not automatically deduct salary or leave. Use Quick visit for official duties, not this form.",
    ["Another HR reviewer must decide a record about themselves or one they submitted."],
    "attendance:view_self",
  ),
  article(
    "profile-photo",
    "employee",
    "Your profile",
    "Upload or change your profile photo",
    "Replace your initials with a clear photo.",
    "/staff/me/profile",
    "photo picture avatar profile upload change",
    [
      "Open My Profile and choose Upload photo underneath your initials.",
      "Choose a JPG or PNG photo smaller than 5 MB. The app prepares a smaller copy so your profile loads quickly.",
      "Wait for Profile photo saved. Your photo replaces the initials. Choose Change photo whenever you need to replace it.",
    ],
    "Your photo remains after you sign out. Signed-in colleagues in your organisation can see it; only you or an authorised HR administrator can change it.",
    ["If uploading fails, your previous photo is kept. Check your connection and try again."],
  ),
  article(
    "family-documents",
    "employee",
    "Your profile",
    "Complete your family's details and documents",
    "Keep spouse and child information up to date.",
    "/staff/me/profile",
    "dependant dependent spouse wife husband child family passport visa ID guardian phone",
    [
      "Open My Profile, then Personal. Add each dependant's name, relationship, date of birth, nationality and contact phone. For a child, use a parent or guardian's phone. Email is optional.",
      "Choose whether a visa is required. Choose No if it does not apply; do not upload an unrelated document just to complete the record.",
      "Save your details. If the change needs HR approval, wait until it is confirmed before uploading documents for a new dependant.",
      "Open Documents, choose Upload Document, then choose the dependant. Select Passport, ID card or Visa and attach a PDF, JPG or PNG up to 10 MB. Upload a passport or ID for each dependant and a visa when required.",
      "HR checks each upload and confirms the official details. You receive a notification when it is verified or needs replacing. A file awaiting verification does not need to be uploaded again.",
      "If you completed your profile previously, your information is kept. A notification and the Documents checklist show what is still missing. Only you and HR-authorised users can view family documents.",
    ],
    "In-app notifications appear under the bell. Eligible updates are also emailed to your work email when HR has enabled company email sending.",
    [
      "Check that each uploaded document shows the correct dependant's name. If a new dependant is missing from the list, ask HR whether your personal-details change is still awaiting approval.",
    ],
    "document:view_self",
  ),
  article(
    "getting-started",
    "employee",
    "Getting started",
    "Your first day in VIA HR",
    "Sign in, finish your details and find your everyday services.",
    "/staff",
    "login portal start mobile dashboard role",
    [
      "Sign in through VIA Portal and open VIA HR. Use your own work account, not a colleague’s account.",
      "Open My Workspace → My Setup. Complete the personal details and documents requested for you.",
      "Open My Profile and check your contact details. HR completes and confirms your employment information.",
      "Use the menu to open leave, attendance, timesheets and other services. On a phone, open the menu button first.",
      "Check My Tasks and the notification bell for anything needing your attention.",
    ],
    "You can use the services available to you while completing your record. Some actions, including leave, may wait for HR confirmation.",
    [
      "HR, managers and Finance are employees too. Their own requests remain under My Workspace.",
      "If a page is missing, check your selected role and ask HR to check your access. Do not use another person’s login.",
    ],
  ),
  article(
    "dashboard",
    "employee",
    "Getting started",
    "Understand your dashboard and working-hours charts",
    "See your hours, balances and tasks without opening every page.",
    "/staff",
    "graph pie chart minutes recorded hours expected not tracked absent today",
    [
      "Open Dashboard. Check today’s attendance separately from the historical working-hours chart.",
      "Choose the chart’s date range. Compare recorded hours with the hours expected for that period.",
      "Open an outstanding task or request to see what needs doing and who is reviewing it.",
      "If a figure looks wrong, open the underlying attendance, leave or timesheet record for the same dates.",
    ],
    "A running attendance counter is an estimate until your clock-out is recorded. Charts for completed days do not include today.",
    [
      "Not tracked means attendance is not required under your current setup; it does not mean absent.",
      "An unfinished clock-in/clock-out pair cannot give a final daily total. Lunch and approved working rules affect the total.",
      "If charts cannot load, use Retry once. If it continues, tell HR the page and date range; do not submit duplicate records.",
    ],
  ),
  article(
    "profile",
    "employee",
    "Getting started",
    "Update your profile and personal details",
    "Keep your contact and emergency information accurate.",
    "/staff/me/profile",
    "phone address emergency dependants joining date visa work permit position department supervisor location",
    [
      "Open My Workspace → My Profile and choose the relevant section.",
      "Update the personal fields you are allowed to change, such as your contact address and emergency contacts.",
      "Review your entries carefully and save. Reopen the section to check the saved information.",
      "Ask HR to correct your joining date, supervisor, VIA email, department, position, location, employment type or visa/work-permit information.",
    ],
    "Confirmed employment information appears on your profile for you to read. HR-controlled information is not an employee-editable form.",
    [
      "Some employment information stays hidden until HR confirms it.",
      "Never put a password or private medical details in an ordinary contact field. Upload sensitive documents only in the appropriate document area.",
    ],
  ),
  article(
    "tasks",
    "employee",
    "Getting started",
    "Find tasks, notifications and pending requests",
    "Know whether a request was submitted and what happens next.",
    "/staff/requests",
    "pending approval approved rejected returned status reminder email notification bell",
    [
      "Open Requests & approvals and choose your own requests.",
      "Find the request and open its details. Read its current status and outstanding approval stage.",
      "If returned, read the reviewer’s comments, correct the details and submit again.",
      "Check My Tasks for assigned actions and the notification bell for updates. Open the linked record before acting.",
    ],
    "Saving a draft is not the same as submitting it. Pending means a decision is still needed; returned means you need to make changes.",
    [
      "Email is an extra channel, not proof of approval. It depends on the company’s email connection and reminder settings.",
      "If the reviewer is wrong or unavailable, ask HR to check your supervisor and the request. Do not create another request just to chase the first.",
    ],
  ),
  article(
    "sign-out",
    "employee",
    "Getting started",
    "Sign out and keep your account safe",
    "Finish your session safely, especially on a shared computer.",
    "/staff/me/profile",
    "logout log out password portal signed out login account",
    [
      "Open your account menu and choose Sign out of VIA HR.",
      "You are taken to VIA Portal. On a shared computer, sign out of the Portal as well.",
      "Close any downloaded payslips or private documents. Remove downloaded copies from shared devices when you no longer need them.",
      "If you cannot sign in again, contact the person who manages your VIA Portal account.",
    ],
    "Signing out of VIA HR and signing out of the Portal are separate actions.",
    ["Do not send your password or a one-time sign-in code to HR, a colleague or Help search."],
  ),
  article(
    "leave",
    "employee",
    "Leave & time off",
    "Apply for leave",
    "Choose the right leave type and follow your request through approval.",
    "/staff/leave",
    "annual holiday vacation sick maternity paternity nationality omani balance",
    [
      "Open My Leave Balances to check your allowance and the leave year.",
      "On My Leave Balances, choose Request Leave. Select Leave Type, Start Date and End Date.",
      "Check the calculated days. Complete Reason for Leave and Covering Colleague when required, and attach any supporting evidence requested for that leave type.",
      "Choose Submit Request. Check Request History or Requests & approvals to confirm the request appears and follow its progress.",
      "Wait for the final decision before treating your leave as approved.",
    ],
    "The request goes through the required reviews. HR is notified as well as the relevant manager; a notification alone is not approval.",
    [
      "A leave type can be limited by nationality or other employment conditions. Ask HR if your eligibility details are wrong.",
      "If submission is blocked, check HR confirmation, your supervisor, balance, dates and overlapping requests.",
    ],
  ),
  article(
    "sick-leave",
    "employee",
    "Leave & time off",
    "Apply for sick leave after being unwell",
    "Ask HR for permission when you could not apply before your absence.",
    "/staff/leave",
    "backdate retroactive sickness yesterday past date medical certificate",
    [
      "Tell HR the dates you were unwell and that you need to submit a late sick-leave request.",
      "HR must allow the backdated request under the applicable rules before you can submit it.",
      "Once permitted, choose Sick Leave and enter the exact absence dates authorised by HR. Submit within 14 days of the permission, not with today’s date as a substitute.",
      "Upload the required medical evidence and submit. Follow the request’s approval status.",
    ],
    "Permission to apply late is not automatic leave approval. Your request still needs its required reviews.",
    ["Do not change an attendance entry to hide an absence. Use the correct leave process."],
  ),
  article(
    "leave-balances",
    "employee",
    "Leave & time off",
    "Check balances, carryover and change a leave request",
    "Understand available leave and avoid losing carried-over days.",
    "/staff/me/leave-balances",
    "old leave may expiry rollover withdraw cancel amend entitlement year",
    [
      "Open My Leave Balances and check the relevant leave year and leave type.",
      "Review used, reserved and available days, plus any carried-over balance and expiry shown.",
      "Plan leave before the carryover deadline and submit it through the normal approval process.",
      "To change or withdraw a request, open the original request and use the action available for its current status. Ask HR if the approved request cannot be changed there.",
    ],
    "A balance can change when requests are approved, cancelled or adjusted. The company’s leave year may not begin in January.",
    [
      "Do not assume every leave type carries forward or shares the same expiry date. HR’s configured policy applies.",
      "A reminder is not an extension of an expiry date. Contact HR early if you cannot use the balance.",
    ],
  ),
  article(
    "attendance",
    "employee",
    "Attendance & visits",
    "Clock in, clock out and check your hours",
    "Record your real arrival and departure when attendance applies to you.",
    "/staff/me/attendance",
    "fingerprint machine biometric flexible 730 830 1630 1730 lunch break minutes",
    [
      "Use your office’s approved clock-in method when you arrive. Head Office may use the fingerprint machine.",
      "Open My Attendance to check that today’s clock-in appears. Allow the office connection to send the record.",
      "Clock out when you finish work, then check the recorded times and hours.",
      "If HR records a company activity, training, approved remote work or an excused closure, your attendance shows that label with credited hours. You do not need to invent clock times. Allocate those hours in your timesheet as usual and submit it for approval. Ask HR if the covered day is incorrect.",
      "If a time is missing or wrong, open that day and request a correction instead of creating another clock-in.",
    ],
    "VIA allows flexible working hours. HR sets the daily working hours and scheduled break. With eight working hours and a one-hour lunch, an 8:30 am arrival normally means a 5:30 pm finish. Attendance totals and timesheet hours include the break: 8:30 am to 5:30 pm is recorded as nine hours. Extra time in the office is not automatically approved overtime.",
    [
      "Coming earlier does not remove your required working hours. For example, 7:30 am–4:30 pm includes the usual lunch hour.",
      "Extra time in the office is not automatically overtime. Overtime needs a separate approved request.",
      "Staff at other locations still complete timesheets and apply for leave even when machine attendance is not required.",
    ],
  ),
  article(
    "missing-clockout",
    "employee",
    "Attendance & visits",
    "Forgot to clock out yesterday?",
    "Send your actual finishing time to HR for review.",
    "/staff/me/attendance",
    "sign out clock out forgot yesterday morning email missing incomplete departure",
    [
      "Open My Attendance and select the day with the missing clock-out, or use the link in the morning email.",
      "Enter the time you actually finished work. Do not guess a standard finishing time.",
      "Submit the correction. Your original clock-in is kept when you are only adding a missing clock-out.",
      "Follow the correction’s status. HR reviews this clock-out-only request.",
    ],
    "You can clock in today while yesterday’s missing clock-out is being resolved. The app does not invent a clock-out for an ordinary forgotten departure.",
    [
      "Morning emails depend on the company’s email setup and current attendance information. You do not need to wait for an email to request a correction.",
      "Changing a clock-in or correcting a whole missing day follows the fuller review process, including manager review.",
      "If a request is already pending, follow that request rather than submitting it twice.",
    ],
  ),
  article(
    "attendance-correction",
    "employee",
    "Attendance & visits",
    "Correct a missing or wrong attendance record",
    "Give the reviewers the actual times for the day in question.",
    "/staff/me/attendance",
    "correction wrong arrival departure absent manager hr missing day",
    [
      "Open My Attendance, find the date and choose its correction action.",
      "Enter the actual clock-in and clock-out details requested. Explain the difference and attach evidence where the form requires it.",
      "Check the date and times before submitting, especially where work continued after midnight.",
      "Read the decision in your requests. If returned or rejected, follow the reviewer’s explanation before resubmitting.",
    ],
    "Full attendance corrections require the relevant manager and HR review. A missing clock-out-only correction is a simpler HR review.",
    [
      "Ask HR if no authorised supervisor is assigned.",
      "If a machine record arrives while your correction is being reviewed, HR may need a fresh request against the updated record.",
    ],
  ),
  article(
    "quick-visit",
    "employee",
    "Attendance & visits",
    "Record a quick site or ministry visit",
    "Use the short visit form for an unplanned work visit, including from your phone.",
    "/staff/me/attendance?action=site-visit",
    "quick visit site ministry home office return official duty mobile",
    [
      "Choose Quick visit on your dashboard or in My Workspace.",
      "Choose Visit type, enter Site / Destination and choose Home or Office under Starting from.",
      "Open Change time, return or add details only if you need to change the suggested time or return plan. If the return time is unknown, keep the appropriate unknown-return choice.",
      "Choose Send to HR and check the visit status. If the plan changes, update or finish the visit using the available visit action.",
    ],
    "Approved official-duty rules determine how attendance is recorded. Leaving from the office still requires your normal arrival clock-in.",
    [
      "Use My Travel for planned trips requiring travel arrangements or costs, not the quick visit form.",
      "A visit request is not permission to claim overtime. Tell HR if your actual visit differs from the approved details.",
    ],
  ),
  article(
    "timesheets",
    "employee",
    "Timesheets & overtime",
    "Complete and submit your timesheet",
    "Record the hours you worked, whether or not you use the office clock.",
    "/staff/timesheets",
    "manual automatic attendance task optional weekly copy hours project activity submit",
    [
      "Open My Timesheets and choose the correct week or period.",
      "Review each working day. If HR enabled attendance-based entries for you, check the suggested hours; otherwise enter your hours manually.",
      "Choose any required project or activity information. A task description is not compulsory unless the form specifically asks for information needed to explain a difference.",
      "Check leave, holidays and breaks. Explain a difference from attendance when prompted.",
      "Save your work, then Submit when the whole period is correct.",
    ],
    "Submission goes through manager review and HR approval before Finance uses the approved timesheet. Automatically filled hours do not automatically approve it.",
    [
      "All locations use timesheets, including staff who do not use machine attendance.",
      "If the week is unavailable or closed, ask HR to check the timesheet period. Do not put the hours in a different week.",
      "If returned, correct the hours or details named by the reviewer and submit again.",
    ],
  ),
  article(
    "overtime",
    "employee",
    "Timesheets & overtime",
    "Request overtime",
    "Request approval for extra work rather than relying on a late clock-out.",
    "/staff/me/overtime",
    "extra hours preauthorisation claim paid overtime finance pending rejected",
    [
      "Open My Overtime and start a request for the actual date and planned extra work.",
      "Enter the hours and purpose, and provide the details requested by the form.",
      "If advance approval is required, submit before the work begins and wait for the decision.",
      "Complete any actual-hours confirmation requested after the work and follow the manager and HR reviews.",
    ],
    "Only the approved overtime process makes extra hours available for the relevant Finance handling. Staying late is not an overtime claim.",
    [
      "Daily, weekly and monthly limits can block a request. Ask HR to explain the applicable limit.",
      "Your own pending and rejected requests remain personal records even if you also work in Finance.",
    ],
  ),
  article(
    "travel",
    "employee",
    "Travel & expenses",
    "Request a planned business trip",
    "Arrange an official trip and keep the approvals together.",
    "/staff/travel",
    "travel planned trip project destination visa accommodation flight cost accounts",
    [
      "Open My Travel and start a travel request.",
      "Enter the destination, travel dates, business purpose and requested arrangements or estimated costs.",
      "Check attachments and submit. Read each outstanding review stage in the request.",
      "If returned, amend the original request and resubmit. Do not book on the assumption that one reviewer’s approval completes the process.",
    ],
    "Travel can require Manager, HR and Finance decisions. The request’s outstanding stages show what is still needed.",
    [
      "A same-day unplanned site or ministry visit normally belongs in Quick Visits.",
      "Changes to dates, costs or arrangements may require a new review. Tell HR before making commitments.",
    ],
  ),
  article(
    "expenses",
    "employee",
    "Travel & expenses",
    "Submit trip expenses and follow reimbursement",
    "Keep receipts and actual costs with the approved trip.",
    "/staff/travel",
    "receipt reimbursement settlement advance currency expense claim",
    [
      "Open the relevant travel request after the trip.",
      "Enter the actual expenses and attach the requested receipts or supporting documents.",
      "Check currency, amounts and any advance already received before submitting.",
      "Follow the reimbursement status and answer any request for corrections.",
    ],
    "Finance reviews the settlement and closes it when the required checks and payment details are complete.",
    [
      "Approval of the trip is not confirmation that reimbursement has been paid. Check the settlement status or ask Finance.",
    ],
  ),
  article(
    "payslips",
    "employee",
    "Pay & documents",
    "View or download your payslip",
    "Find the payslip Finance has issued to you.",
    "/staff/payslips",
    "salary pay slip payroll month download wrong replacement",
    [
      "Open My Payslips and find the correct pay period.",
      "Open or download your payslip on a private device.",
      "Check your name, period and amounts. Contact Finance if any item appears wrong.",
      "If Finance replaces a payslip, use the current version rather than an older downloaded copy.",
    ],
    "Employees see their own payslips. Finance uploads and manages issued payslips.",
    [
      "If there is no payslip, ask Finance whether it has been uploaded. An empty list is not proof that salary was unpaid.",
    ],
  ),
  article(
    "personal-documents",
    "employee",
    "Pay & documents",
    "Find your documents and insurance information",
    "Keep personal documents separate from the company’s shared policies.",
    "/staff/me/profile",
    "passport visa work permit insurance card table benefits upload expiry document",
    [
      "Open My Profile and choose Documents or the relevant insurance section.",
      "Read the requested document type and upload the document only where you are allowed to do so.",
      "Check the document details and any expiry date displayed.",
      "Upload your own visa and health insurance card under My Profile, Documents, Upload Document. HR reviews your upload and confirms official visa details. Work permits remain managed by HR.",
      "Open Policies & Company Documents and choose Health insurance to download the Table of Benefits assigned to you. HR uploads these shared documents; you do not need to upload your own copy.",
    ],
    "Your personal records are not the same as the colleague contact directory. Access depends on the document and the viewer’s responsibilities.",
    [
      "For coverage questions, read the insurance table of benefits and ask HR or the insurer. Do not assume that uploading a card changes your cover.",
    ],
  ),
  article(
    "policies",
    "employee",
    "Pay & documents",
    "Read policies or ask a policy question",
    "Find published company instructions and the documents behind an answer.",
    "/staff/company-library",
    "sop policy handbook ai chat ask questions knowledge company library",
    [
      "Open Policies & Documents and choose the library section.",
      "Find the policy you need and open the published document.",
      "Use the question area to ask a clear question about the available policies.",
      "Read the answer and its supporting document references. Open the source before relying on an important detail.",
    ],
    "Policy answers are based on the available published material. This Help guide explains how to use the app; company policies explain company rules.",
    [
      "If there is no supported answer, ask HR. Do not treat a missing answer as permission.",
      "You can only read documents shared with you. Private HR company records are not part of the employee library.",
    ],
  ),
  article(
    "directory",
    "employee",
    "People & opportunities",
    "Find a colleague or your reporting line",
    "Look up work contacts and see how the organisation is arranged.",
    "/staff/employees",
    "directory employee email phone colleague department country manager organisation organogram anniversary",
    [
      "Open Employee Directory and search for the colleague’s name.",
      "Use the available department or location filters to narrow the list.",
      "Read their shared work contact details and position.",
      "Open Organisation Chart to understand reporting lines, or Work Anniversaries to see joining anniversaries.",
    ],
    "The colleague directory is for contact information. It is not access to another person’s confidential employment file.",
    [
      "Ask HR if a supervisor, position or location is wrong. Employees do not rearrange the organisation chart themselves.",
    ],
  ),
  article(
    "opportunities",
    "employee",
    "People & opportunities",
    "Apply for a vacancy or recommend someone",
    "Use open opportunities for an internal application or a referral.",
    "/staff/opportunities",
    "job vacancy internal apply referral recommend friend cv resume recruitment",
    [
      "Open Opportunities and choose an available role. Read its requirements before starting.",
      "Choose the application or recommendation action, depending on whether you are applying yourself or referring someone.",
      "Enter accurate contact details and upload the requested CV. Get the person’s permission before sharing their details.",
      "Submit and follow any status or follow-up shown in the app.",
    ],
    "HR reviews recommendations. An approved recommendation can move into interview preparation; a declined recommendation can remain in the candidate pool for future opportunities.",
    [
      "Recommending someone is not a job offer or interview guarantee.",
      "For your own internal application, keep your existing employee identity; do not create a second employee account.",
    ],
  ),
  article(
    "performance",
    "employee",
    "Development",
    "Set objectives and complete your appraisal",
    "Agree what you are working towards before completing a performance review.",
    "/staff/me/performance",
    "goals objectives appraisal self assessment review manager cycle evidence",
    [
      "Open My Performance and check the active review period.",
      "Create or review your objectives with clear outcomes, dates and any requested measures.",
      "Follow the objective agreement process with your manager before the appraisal stage.",
      "When the review opens, complete your self-assessment using evidence of your work and submit it.",
      "Read manager feedback and complete any acknowledgement or follow-up requested.",
    ],
    "Objectives and appraisal belong to the relevant review period. HR manages the overall review timetable.",
    [
      "If objectives or an active review are missing, ask your manager or HR rather than creating a review for the wrong period.",
    ],
  ),
  article(
    "training",
    "employee",
    "Development",
    "Request training and record completion",
    "Ask for development support and keep your learning record up to date.",
    "/staff/me/training",
    "course certificate session learning request cost mandatory",
    [
      "Open My Training and review available courses or assigned learning.",
      "Start the relevant request and enter the course, dates and cost information requested.",
      "Submit and wait for the required decision before committing company funds.",
      "After attending, record completion and upload the certificate or evidence requested.",
    ],
    "HR can verify training records and assign required courses. A request and a verified completion are different stages.",
    [
      "If an open request already exists, follow it instead of submitting the same course again.",
      "A free course may need fewer details than paid discretionary training; follow the fields shown.",
    ],
  ),
  article(
    "onboarding",
    "employee",
    "Joining & leaving",
    "Complete your joining checklist",
    "See the actions you and other teams need to finish.",
    "/staff/me/onboarding",
    "onboarding setup new joiner equipment tasks documents probation",
    [
      "Open My Setup or My Tasks and choose your joining checklist.",
      "Complete each task assigned to you, including requested details, documents or acknowledgements.",
      "Save or submit each item and check its new status.",
      "Contact HR if an item belongs to someone else or a completed step is still waiting for review.",
    ],
    "Some tasks are completed by HR, IT or another assigned person. You cannot finish their tasks on their behalf.",
    ["Submitting a document is not always the final step; HR may need to verify it."],
  ),
  article(
    "leaving",
    "employee",
    "Joining & leaving",
    "Complete your leaving and equipment-return tasks",
    "Follow the agreed handover and clearance process.",
    "/staff/my-tasks",
    "offboarding resignation leaving return laptop asset equipment clearance handover",
    [
      "Open My Tasks and review any leaving tasks assigned to you.",
      "Complete the requested handover and arrange return of company equipment with the responsible person.",
      "Provide the requested confirmation or evidence in the task.",
      "Check with HR about any outstanding clearance or final documents.",
    ],
    "HR completes the overall offboarding case after the required clearances. Returning an item and completing the whole case are separate steps.",
    [
      "Do not remove company records or close somebody else’s account yourself. Follow the assigned handover instructions.",
    ],
  ),
  article(
    "help-problem",
    "employee",
    "Getting started",
    "Something is missing or will not save",
    "Give HR enough information to help without sharing private credentials.",
    "/staff",
    "error loading slow blank upload save permission denied support phone search",
    [
      "Check your connection and the page’s filters, dates and selected role.",
      "Read any message beside the field or at the top of the page. Correct missing required details.",
      "If a save or submission is uncertain, reopen the record to check whether it succeeded before trying again.",
      "Tell HR the page name, time, what you tried and the message shown. Include a screenshot with private details hidden.",
    ],
    "HR can check the relevant record, your reporting line and access, or ask the system administrator for help.",
    [
      "Never include passwords, sign-in codes, private CVs or medical documents in a general support screenshot.",
      "For an upload, follow that form’s file type and size rules. Different document areas may have different limits.",
    ],
  ),
];
