import { article } from "./guide.ts";

export const hrGuide = [
  article(
    "hr-reminder-settings",
    "hr",
    "HR essentials",
    "Change reminder settings",
    "Choose when the company receives useful reminders.",
    "/staff/settings?section=reminders",
    "notifications reminders travel training expiry leave carryover missing clock out morning offer deadlines",
    [
      "Open HR Settings → Reminder Settings. Each card controls one kind of reminder.",
      "Turn a reminder on or off, then set its waiting hours, warning days or morning window. Separate warning days with commas; 0 means the expiry day.",
      "Set the carried-over leave target as month-day, for example 04-30 for 30 April. This only changes reminders, not leave entitlements or expiry rules.",
      "Choose Save reminder settings. The saved rules apply across the company. Leave and training approvals are unchanged.",
      "For emails, also enable Approval emails & reminders in Google Calendar & Meet. Missing-clock-out reminders remain in the next morning, in company local time.",
    ],
    "Changes do not recall messages already sent. Document expiry reminder days remain in Company Setup.",
    ["Only HR and Super Admin can change these rules."],
    "leave:admin_all",
  ),
  article(
    "hr-start",
    "hr",
    "HR essentials",
    "Where to find your HR work",
    "A simple map of the HR workspace and the people responsible for decisions.",
    "/staff",
    "hr dashboard overview charts employee filter approvals administration setup",
    [
      "Use Employees for employee records, the organisation chart, joining and leaving.",
      "Use Time & Leave for attendance, visits, balances and timesheets. Use Approvals for requests waiting for a decision.",
      "Use Recruitment for vacancies, CVs, recommendations, interviews and offers.",
      "Use Performance & Training for development, and Documents for files, policies and expiry dates.",
      "Use HR Settings for the settings your role can change. Ask Super Admin for company-wide setup you cannot open.",
    ],
    "My Workspace remains your own employee area. Choosing an HR role does not remove your own employee responsibilities.",
    [
      "An HR role is not the same as Finance or Super Admin. Access and approval checks still apply.",
      "Use dashboard employee, department, location and date filters where available. A filtered chart is not necessarily an organisation-wide total.",
    ],
  ),
  article(
    "hr-employee",
    "hr",
    "Employee records",
    "Add an employee and confirm employment details",
    "Create one accurate employee record and complete the information only HR should manage.",
    "/staff/employees",
    "new import employee joining start date supervisor email department position location employment type visa confirm",
    [
      "Search Employee Directory first to avoid creating a second record for the same person.",
      "Open the employee record or use the add-employee action. Enter the person’s correct identity and contact details.",
      "Complete VIA start date, VIA email, supervisor, department, position, work location and employment type in the employment section.",
      "Complete the visa or work-permit information that applies and review the supporting documents.",
      "Check the supervisor has the right approval access, then confirm the employment information using the form’s action.",
    ],
    "Confirmed employment details appear on the employee’s profile. HR-owned fields cannot be changed by the employee.",
    [
      "A future start date or effective date is not permission to make a change early.",
      "Use the import page’s supplied format for multiple employees. Review errors and duplicates before completing an import.",
      "In Update Employment Records, use Add department, Add position, Add work location, Add employment type, Add project or Add grade for a missing option. Enter its name (and start date for a project), then choose Add and select. Save Changes to assign it to the employee. Adding an option alone does not change the employee record.",
    ],
    "employee:manage_all",
  ),
  article(
    "hr-employment-change",
    "hr",
    "Employee records",
    "Change employment details now or on a future date",
    "Record transfers and other employment changes with the correct start date.",
    "/staff/employees",
    "promotion salary transfer location department future effective pending reason employment history",
    [
      "Open the employee and choose the employment update action.",
      "Change only the intended fields and choose the date the change should take effect.",
      "Provide a reason when the form requires one, especially for sensitive changes. Routine setup changes may not require a reason.",
      "Review the old and new information, save, then check whether the change is current or pending.",
    ],
    "Future-dated changes stay pending until their effective date. Employment history is not ordinary colleague-directory information.",
    [
      "If the current record has not changed, check whether the effective date is in the future.",
      "Do not move an effective date backwards simply to make a pending change appear immediately.",
    ],
    "employee:manage_all",
  ),
  article(
    "hr-employee-file",
    "hr",
    "Employee records",
    "Find everything for one employee",
    "Open the employee’s record instead of searching every module separately.",
    "/staff/employees",
    "search individual graph chart timesheet leave balance documents attendance travel training equipment profile",
    [
      "Search Employee Directory by name and open the correct person.",
      "Choose the relevant section: attendance, leave, timesheets, documents, travel, training, performance or joining and leaving.",
      "Check the dates or period before reading a balance or total.",
      "Use the relevant module for an action that is not available from the profile.",
    ],
    "HR can review information within its access. Finance-only records and protected administration actions still have separate permissions.",
    [
      "Confirm the employee identity before uploading a document or changing a record.",
      "Do not share the HR profile with colleagues as a substitute for the public contact directory.",
    ],
    "employee:view_all",
  ),
  article(
    "hr-org-chart",
    "hr",
    "Employee records",
    "Arrange the organisation chart",
    "Keep reporting lines clear, from company leadership to individual teams.",
    "/staff/org-chart",
    "organogram org chart ceo country manager supervisor hierarchy reporting top root",
    [
      "Open Organisation Chart and find the employee or manager you need to arrange.",
      "Use the available edit controls to set the reporting relationship. Check the employee’s supervisor in their employment record too.",
      "Save and review the resulting chart, including the top-level people and the country or department structure.",
      "Check that the intended supervisors can access the approvals assigned to them.",
    ],
    "The chart represents saved reporting relationships. A job title alone does not grant approval access.",
    [
      "A person cannot report to themselves or create a loop in the reporting chain.",
      "If the chart does not change, check the save result and whether the employment change has a future effective date.",
    ],
    "employee:manage_all",
  ),
  article(
    "hr-onboarding",
    "hr",
    "Joining & leaving",
    "Manage a new joiner’s onboarding",
    "Assign a clear checklist to the employee and the teams helping them start.",
    "/staff/onboarding",
    "onboarding template checklist tasks it equipment access probation new joiner",
    [
      "Open Onboarding and find or create the appropriate employee case.",
      "Choose the relevant checklist and review the tasks, due dates and assigned owners.",
      "Assign personal tasks to the employee and equipment or access tasks to the responsible team members.",
      "Review submitted evidence and complete the HR checks. Follow overdue or blocked items.",
      "Complete the case only when the required tasks and checks are finished.",
    ],
    "Task owners see their assigned work in My Tasks. HR remains responsible for reviewing the overall case.",
    [
      "Use an existing employee record for an internal move, not a new starter record.",
      "Changing a checklist template is not the same as completing a task in an existing case.",
    ],
    "onboarding:manage_all",
  ),
  article(
    "hr-offboarding",
    "hr",
    "Joining & leaving",
    "Manage offboarding and final clearance",
    "Coordinate handover, equipment and access before closing the case.",
    "/staff/offboarding",
    "offboarding resignation terminate leaving clearance cancel completion hr",
    [
      "Open Offboarding and create or review the case for the correct employee and leaving date.",
      "Review the checklist and assign handover, equipment, Finance and access-removal tasks to their owners.",
      "Track completion and evidence. Follow up on outstanding clearances rather than marking them complete for someone else.",
      "When all required checks are satisfied, HR completes the case using the completion action.",
    ],
    "A cancelled case cannot be completed. HR completion is a business clearance step, not a reason to grant technical administration access.",
    [
      "You cannot approve or complete your own case where an independent reviewer is required.",
      "If the leaving plan changes, update or cancel the case through the appropriate action before continuing.",
    ],
    "offboarding:manage_all",
  ),
  article(
    "hr-equipment",
    "hr",
    "Joining & leaving",
    "Assign, return and reassign equipment",
    "Keep a clear record of who currently holds each company item.",
    "/staff/employees",
    "asset laptop equipment return reassign available condition serial handover it",
    [
      "Open the employee’s Equipment section and review current assignments.",
      "Assign the correct available item and record the handover details requested.",
      "When it is returned, record the actual return and condition using the return action.",
      "Check that the item is available before assigning it to another employee.",
    ],
    "A completed return releases the item for the supported reassignment process. Old assignment history remains separate from the new holder.",
    [
      "Do not create a duplicate item to work around an unfinished return. Resolve the existing assignment first.",
    ],
    "employee:manage_all",
  ),
  article(
    "hr-approvals",
    "hr",
    "Requests & approvals",
    "Review requests and follow outstanding decisions",
    "Find the next responsible reviewer without approving outside your role.",
    "/staff/requests",
    "approval inbox pending returned reject approve reminders email escalation organisation",
    [
      "Open Requests & approvals and select the organisation or approval view available to you.",
      "Filter for the request type or status you need. Open the original request and read its details.",
      "Check the outstanding stage, assigned reviewer, dates and attachments before deciding.",
      "Approve, return for correction or decline using the available action. Give a useful explanation when requested.",
      "Reopen the request to verify the decision and the next stage.",
    ],
    "One approval may move a request to another reviewer rather than complete it. Employees can follow their own request status.",
    [
      "If a request is stuck with the wrong supervisor, correct the reporting line and resolve the assignment through the supported process.",
      "Do not approve your own request where independent approval is required, even when you have an HR or Super Admin role.",
    ],
    "employee:view_all",
  ),
  article(
    "hr-leave-review",
    "hr",
    "Requests & approvals",
    "Review leave and permit late sick-leave applications",
    "Check eligibility, dates and the required review stages.",
    "/staff/leave-approvals",
    "approve leave sick backdate retroactive permission line manager notification",
    [
      "Open Leave Approvals and find the pending request.",
      "Review the leave type, eligibility, dates, allowance and any required evidence.",
      "Check the manager’s stage and complete the HR action when it is your turn.",
      "For late sickness, open Leave Management → Permit backdated sick leave. Select the employee, first and last sick day, and reason, then Grant permission. It allows one submission for those exact dates within 14 days; normal evidence and approvals still apply.",
      "Check the final status and let the employee correct any returned request.",
    ],
    "HR notifications and permission to apply late do not themselves approve leave.",
    [
      "Use the actual absence dates and the employee’s relevant leave year.",
      "Do not change nationality or other employment facts just to make an ineligible leave type available.",
    ],
    "leave:admin_all",
  ),
  article(
    "hr-leave-balances",
    "hr",
    "Time & leave",
    "Manage leave balances, calendars and carryover",
    "Review allowances and make controlled corrections for the right leave year.",
    "/staff/leave-admin",
    "balance adjustment rollover entitlement year calendar old leave expiry may carryover export",
    [
      "Open Leave Management and choose balances, records or the absence calendar.",
      "Select the employee, leave type and leave year before comparing balances.",
      "For a genuine correction, use the adjustment action and provide the required explanation. Have another authorised person handle your own adjustment.",
      "Before annual rollover, check the selected leave year and policy rules. Run the supported rollover action once and review the result.",
      "Review expiring carried-over leave and encourage employees to plan within the applicable deadline.",
    ],
    "Balances, requests and rollover follow the company’s configured leave-year start, not an assumed January start.",
    [
      "Do not repeat rollover just because a page is slow. Check whether the first action completed.",
      "Pending requests can reserve days. Look at the request history before treating a lower balance as an error.",
    ],
    "leave:admin_all",
  ),
  article(
    "hr-leave-policy",
    "hr",
    "HR settings",
    "Set leave allowances and eligibility rules",
    "Keep leave rules aligned with the company’s approved policy.",
    "/staff/leave-policies",
    "policy nationality omani only evidence notice annual sick carryover expiry year start accrual",
    [
      "Open HR Settings → Leave Policies and choose the leave type or policy to review.",
      "Set the applicable allowance, eligibility, notice and evidence requirements shown in the form.",
      "Review nationality conditions for leave restricted to Omanis, and check the carryover and expiry rules where available.",
      "Save the policy, then check a relevant employee’s eligibility and balance before announcing the change.",
    ],
    "The saved rules control the available leave process. They are not a substitute for HR confirming the company’s approved policy.",
    [
      "Do not assume all leave types share the same entitlement or supporting-document requirements.",
      "If a company-wide leave-year option is not available in your role, ask Super Admin to update the relevant company setting.",
    ],
    "leave:admin_all",
  ),
  article(
    "hr-attendance",
    "hr",
    "Time & leave",
    "Manage attendance and Head Office tracking",
    "Show real attendance without marking other locations absent for not using a machine.",
    "/staff/attendance",
    "head office location department filter not tracked absent records office setup hours flexible lunch",
    [
      "Open Attendance & Visits. Choose the date and employee, department or location filters you need.",
      "Use Office Setup to review which location is Head Office and who is required to record attendance.",
      "Check employee location assignments and any individual tracking choices, including their effective dates.",
      "Review real clock-in and clock-out records separately from missing-record exceptions.",
      "Use Review Corrections for requested changes, rather than inventing a time to remove an absence.",
    ],
    "Machine attendance is normally a Head Office requirement. Employees elsewhere still use leave and timesheets; Not tracked is not an absence.",
    [
      "Saved punches remain visible even when the employee is not currently required to use attendance.",
      "If totals disagree, compare the same date, filters, employee assignment and complete clock-in/clock-out pair.",
      "Office zones and the employee’s work location are different settings; an empty zone list does not prove there are no punches.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-machine",
    "hr",
    "Time & leave",
    "Connect the attendance machine and match employees",
    "Keep the office machine, office computer and VIA HR working together.",
    "/staff/attendance",
    "terminal fingerprint biometric connector pair one time code serial ip port commkey users match automatic startup missing name",
    [
      "Open the terminal area in Attendance & Visits and register the correct office terminal if needed.",
      "Use Connect to obtain the pairing code. Enter it in the office attendance connector with the actual machine details and VIA HR address.",
      "Keep the office computer connected to the office network and allow the connector to start automatically when it restarts.",
      "Check the registered terminal and its latest received information in VIA HR.",
      "Review terminal users needing attention and match each machine identity to the correct employee. Check the name and employee details carefully.",
    ],
    "Pairing should be kept between restarts. Matching links existing attendance identities to employee records; it does not require employees to enrol again just to fix a name match.",
    [
      "The machine being reachable on the office computer does not prove that VIA HR has received its records. Check both connections.",
      "If a person is missing, check the machine’s user list, the connector’s latest transfer and unmatched terminal users.",
      "Do not reset the machine, clear attendance logs or delete a terminal as a troubleshooting shortcut. Ask the administrator to check the connection first.",
      "Never share a pairing code or the machine’s communication key in a public screenshot.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-corrections",
    "hr",
    "Requests & approvals",
    "Review attendance corrections and quick visits",
    "Check actual work times without creating automatic overtime.",
    "/staff/attendance/corrections",
    "forgot clock out yesterday missing correction site ministry visit home office hr approval",
    [
      "Open Attendance Corrections and compare the proposed times with the original record and explanation.",
      "A request that only adds yesterday’s missing clock-out can come directly to HR. Full corrections still follow manager review.",
      "Approve or decline using the available decision action. If the underlying record changed, ask for a corrected request rather than overwriting new evidence.",
      "Review quick visits in Attendance & Visits. Check origin, destination and the expected return or finish information before approving.",
    ],
    "Approved corrections update attendance through the controlled review process. Approved official-duty attendance follows the visit rules; neither creates an overtime claim.",
    [
      "The morning missing-clock-out email is not an instruction to leave work. There is no ordinary end-of-day go-home reminder.",
      "Do not enter an assumed standard finishing time when the employee has not confirmed their actual departure.",
    ],
    "attendance:manage_all",
  ),
  article(
    "hr-timesheets",
    "hr",
    "Time & leave",
    "Monitor and approve employee timesheets",
    "Make sure every timesheet receives HR approval before Finance uses it.",
    "/staff/timesheet-monitoring",
    "timesheet monitor missing submitted returned approved manual automatic attendance finance",
    [
      "Open Employee Timesheets and select the employee, period and available filters.",
      "Review missing, draft, submitted and returned sheets separately.",
      "Open Timesheet Approvals for sheets ready for your review. Compare working hours, leave and any explanation of differences.",
      "Return a sheet with a clear correction request when necessary, or approve it when the required checks are complete.",
      "Check the final status before treating it as ready for Finance.",
    ],
    "Manager review comes before the required HR approval. Attendance-based entries still need review; task descriptions are not a blanket requirement.",
    [
      "Do not turn extra attendance time into approved overtime. Use the separate overtime process.",
      "A manual-timesheet employee outside Head Office should not be treated as absent merely because there are no machine punches.",
    ],
    "timesheet:admin_all",
  ),
  article(
    "hr-timesheet-settings",
    "hr",
    "HR settings",
    "Set timesheet periods and working-hour rules",
    "Choose how new timesheet weeks work and manage closed periods.",
    "/staff/timesheet-settings",
    "weekly start deadline daily hours lunch tolerance copy period generate close reopen lock overtime limits attendance prefill",
    [
      "Open Timesheet Settings. Review the week’s start day, submission deadline and standard daily hours.",
      "Standard Daily Hours means working time without breaks: use 8 for an eight-hour day plus a one-hour lunch. Saving this value updates attendance, timesheets and Company Setup together. To change the break, open Attendance & Visits → Office Setup → Attendance Policy and set Break starts at and Default break minutes. Use 0 minutes for no scheduled break.",
      "Review overtime limits, advance-approval rules and the allowed difference between attendance and a timesheet. HR approval after supervisor review remains required.",
      "Choose whether staff can copy the previous week and review the payroll-lock choice. Save Configuration.",
      "Use Period Generation with the intended start and end dates, then check the generated weeks.",
      "Use the period list to close completed periods or reopen one with the required reason when corrections are authorised.",
    ],
    "Configuration changes apply to new periods and timesheets. Closing a period stops employee creation, editing and submission in that period.",
    [
      "For Head Office staff, review the employee’s attendance-to-timesheet choice in attendance setup; it is not automatic approval.",
      "Flexible arrival times do not remove the daily hours requirement or the configured lunch deduction.",
    ],
    "timesheet:admin_all",
  ),
  article(
    "hr-overtime",
    "hr",
    "Requests & approvals",
    "Review overtime for Finance",
    "Check the separate overtime request, not simply the time spent in the office.",
    "/staff/overtime-approvals",
    "overtime approved actual hours supervisor hr finance ledger advance",
    [
      "Open Overtime Approvals and select a request ready for your stage.",
      "Check the purpose, requested or actual hours, manager decision and applicable limits.",
      "Return it for correction or complete the HR decision.",
      "Use the approved overtime information for the Finance handover; do not substitute raw attendance totals.",
    ],
    "Approved overtime appears in the relevant ledger for Finance handling.",
    ["A long day or a late clock-out does not create an overtime entitlement in the app."],
    "overtime:admin_all",
  ),
  article(
    "hr-travel",
    "hr",
    "Requests & approvals",
    "Coordinate travel approval and settlement",
    "Keep Manager, HR and Finance decisions aligned.",
    "/staff/travel-hr-approvals",
    "travel planned trip accounts manager finance approval reimbursement closure receipt",
    [
      "Open HR Travel Approvals and inspect the purpose, dates, arrangements and estimated costs.",
      "Check the outstanding Manager and Finance stages alongside the HR stage.",
      "Complete your decision or return the request with clear changes required.",
      "After the trip, follow actual expenses and supporting receipts through the settlement process.",
      "Finance completes reimbursement closure using its authorised action.",
    ],
    "HR approval alone does not replace Manager or Finance approval, and trip approval is separate from payment settlement.",
    [
      "Use quick visits for short unplanned site or ministry duties, not a full travel request unless arrangements or costs require it.",
    ],
    "travel:hr_review",
  ),
  article(
    "hr-vacancy",
    "hr",
    "Recruitment",
    "Create a vacancy and a rich job description",
    "Prepare an editable role description, requirements and compulsory criteria.",
    "/staff/vacancies",
    "ai generate job description title years experience requirements compulsory compensation visibility publish close archive",
    [
      "Open Vacancies and start a vacancy. Enter the role, work location and experience level accurately.",
      "Use the job-description generation action if available, then review every section of the draft.",
      "Check responsibilities, requirements, compulsory criteria, compensation and visibility. Add or remove items to match the real role.",
      "Confirm any location-specific licence or work eligibility requirement with the responsible HR person before treating it as compulsory.",
      "Follow the vacancy’s approval and publishing actions. Review the published details and close or archive through the available action when recruitment is finished.",
    ],
    "Generated content is a draft for HR to edit, not a verified statement of legal requirements or company compensation policy.",
    [
      "Do not publish private salary information unintentionally; check the visibility choices.",
      "Closing a vacancy before its planned hiring is complete may require an explanation.",
    ],
    "recruitment:manage_vacancies",
  ),
  article(
    "hr-cv-intake",
    "hr",
    "Recruitment",
    "Upload CVs and review extracted details",
    "Keep the original CV and check proposed candidate information.",
    "/staff/candidates/intake",
    "cv resume upload original processing queue unreadable scanned text duplicate version import",
    [
      "Open Incoming CVs and choose the relevant vacancy when uploading CVs for a role.",
      "Upload the original files in the format and size accepted by the form.",
      "Follow processing status. Open unreadable or uncertain items and inspect the original document.",
      "Review proposed work history, skills, education, certificates and languages before confirming changes to candidate details.",
      "Resolve duplicates against the existing candidate rather than creating another identity for the same person.",
    ],
    "Processing prepares information for review; it should not be treated as HR confirmation of every fact in a CV.",
    [
      "If processing fails, check the file and retry through the available action. Do not repeatedly upload the same file to chase a pending job.",
      "A revised CV can change the current assessment. Review the current version before shortlisting.",
    ],
    "recruitment:manage_candidates",
  ),
  article(
    "hr-screening",
    "hr",
    "Recruitment",
    "Rank candidates and choose how many to shortlist",
    "Use current CV information and the vacancy’s requirements to support a human decision.",
    "/staff/candidates",
    "screening ranking rank top 10 top 20 number shortlist score match compulsory not confirmed preparation assessment",
    [
      "Open the relevant vacancy or candidate assessment area and check that the job requirements are correct.",
      "Wait for the current CV preparation to finish and review any processing problems.",
      "Read the match assessment and compulsory-criteria evidence. Missing information is not the same as confirmed failure.",
      "Choose the number of candidates you want to review, such as 10 or 20, using the available shortlist or assessment controls.",
      "Review the selected candidates and original CVs before deciding whom to progress.",
    ],
    "Ranking is a preliminary aid, not a guarantee of suitability or an automatic hiring decision. Current valid information should drive the comparison.",
    [
      "Do not confirm a compulsory criterion merely because a candidate has a high overall score.",
      "Resolve Needs HR Review, Not Confirmed and processing problems before relying on those results.",
    ],
    "recruitment:view_candidates",
  ),
  article(
    "hr-candidate-pool",
    "hr",
    "Recruitment",
    "Search the talent pool and manage candidate contact",
    "Consider existing candidates as well as people who applied to this vacancy.",
    "/staff/candidates",
    "talent database pool fit role search skills experience contact tracker import candidate status notes",
    [
      "Open Candidate Pool and search using the role-relevant skills and experience available in the filters.",
      "To download original CVs together, filter the Candidate Pool to the people you need, choose Download CVs (ZIP), review the file count and choose Download ZIP. All saved CV versions are included in separate folders, with their original contents unchanged. EXPORT-SUMMARY.txt lists candidates without a CV. Keep the page open until the download starts. For more than 250 MB, use smaller filtered groups. Export CSV downloads candidate details, not CV documents.",
      "Open a potential match and review the current CV, previous applications and contact history.",
      "Use the supported vacancy or assessment action to consider the person for the new role.",
      "Use Contact Tracker to record outreach and follow-up so colleagues do not contact the person repeatedly.",
      "Keep confirmed candidate details accurate and distinguish private review notes from information intended for the candidate.",
    ],
    "A person can remain in the pool without being on a current interview list.",
    [
      "Check the person’s interest and permission before reusing their information for a new opportunity. Follow company retention rules.",
      "An old high score for another role is not proof of fit for a new vacancy.",
    ],
    "recruitment:view_candidates",
  ),
  article(
    "hr-referrals",
    "hr",
    "Recruitment",
    "Approve or decline staff recommendations",
    "Review referrals without losing potentially useful candidates.",
    "/staff/recommendations",
    "referral recommendation staff approve decline interview pool",
    [
      "Open Recommendations and select the submitted person and vacancy.",
      "Review the CV, contact details and recommendation. Check for an existing candidate first.",
      "Approve the recommendation to move it into the supported interview-preparation flow, or decline it with the information required.",
      "Check the resulting candidate status and interview list before scheduling.",
    ],
    "Declining a recommendation need not delete the candidate from the talent pool. Approval does not itself schedule or confirm an interview.",
    [
      "Do not confuse a recommended candidate with an employee record. Employment starts through the hiring and joining process.",
    ],
    "recruitment:manage_candidates",
  ),
  article(
    "hr-interview",
    "hr",
    "Recruitment",
    "Schedule interviews with Google Calendar and Meet",
    "Connect the agreed HR account and keep invitations with the interview record.",
    "/staff/interviews",
    "google calendar calender meet connect sign in once interview invite panel reschedule cancel scoring template",
    [
      "Open Interviews and choose the candidate and vacancy.",
      "If prompted, connect the agreed HR Google account and grant the requested calendar access. Portal sign-in alone does not connect the calendar.",
      "To change the organising email, open Google Calendar & Meet, enter the new Organising email and choose Save account and reconnect. Then sign into that Google account. Approval emails pause until you grant email access again. If interviews are already linked, ask your administrator to move the bookings first; changing the address does not move meetings between calendars.",
      "Choose the interview date, time, time zone, interviewers and meeting details. Check the candidate email before scheduling.",
      "Check the saved interview and invitation or meeting status; do not assume an unfinished connection sent an invitation.",
      "Use the interview’s reschedule or cancel action when plans change. Ask assigned interviewers to complete their scorecards.",
    ],
    "The saved connection can be reused until it is revoked or requires reconnection. Calendar access and approval-email access are separate permissions.",
    [
      "If connection setup is unavailable, ask the administrator to finish the company’s Google setup; do not share the HR password.",
      "Check both candidate and panel availability and the time zone. A visible meeting link is not proof that everyone has accepted.",
    ],
    "recruitment:manage_interviews",
  ),
  article(
    "hr-offers",
    "hr",
    "Recruitment",
    "Prepare, approve and send an offer",
    "Keep offer preparation, manager approval and sending as distinct steps.",
    "/staff/offers",
    "offer draft final approval assigned manager return send awaiting delivery failed manual evidence sent",
    [
      "Open Offers and prepare the correct candidate’s offer with the agreed position, compensation and joining details.",
      "Assign the authorised manager and submit for approval.",
      "If returned, amend the offer and send it back for review. HR preparation does not replace assigned-manager approval.",
      "After approval, choose Mark Ready to Send. Send the approved offer to the candidate yourself using the agreed company email process.",
      "In Record manual sending, enter the actual recipient and sending time, provide the sent-message evidence requested, confirm that you sent the approved terms, then choose Record as manually sent.",
    ],
    "The flow is HR prepares → assigned manager approves or returns → HR sends. The manual-sending form records an email you already sent; it does not send the email for you.",
    [
      "Check the recipient and attachment carefully before sending. An approved offer is not yet a delivered offer.",
      "Record the candidate’s acceptance, decline or offer expiry using the available action after sending. Do not mark acceptance merely because the message was sent.",
    ],
    "recruitment:manage_candidates",
  ),
  article(
    "hr-hire",
    "hr",
    "Recruitment",
    "Move a successful candidate into employment",
    "Create the correct joining process without duplicating an existing employee.",
    "/staff/candidates",
    "hire convert conversion internal employee email identity onboarding offer accepted",
    [
      "Open the successful candidate and check the required offer and hiring stages are complete.",
      "Confirm whether this is a new external hire or an existing employee moving internally.",
      "Use the conversion or hiring action and review the proposed employee identity and work email.",
      "For an internal hire, use the existing employee record and the appropriate employment change.",
      "Review the resulting employment details and onboarding case.",
    ],
    "A successful internal applicant should not become a second employee with a different identity.",
    [
      "Check possible duplicate emails and names before confirming. Ask the account administrator if an identity needs correction.",
    ],
    "recruitment:manage_candidates",
  ),
  article(
    "hr-performance",
    "hr",
    "Performance & training",
    "Run an objective-setting and appraisal cycle",
    "Set the timetable, participants and review structure before appraisals begin.",
    "/staff/performance/cycles",
    "performance cycle objective goal appraisal template team manager review launch close",
    [
      "Open Performance Cycles and create the period with the correct dates and participants.",
      "Choose the appropriate objectives and review template, and check manager assignments.",
      "Ensure objectives are created and agreed before the appraisal stage.",
      "Monitor employee self-assessments and manager reviews through Team Performance.",
      "Follow up on incomplete stages and close the cycle only when the required process is complete.",
    ],
    "A review is tied to its cycle and objectives. A dashboard percentage is a progress indicator, not a substitute for reading the review.",
    [
      "If a supervisor cannot review, check their reporting relationship and approval access.",
      "Ask Super Admin for template setup where that company-wide setting is not available to HR.",
    ],
    "performance:manage_all",
  ),
  article(
    "hr-training",
    "hr",
    "Performance & training",
    "Manage courses, sessions and training records",
    "Plan learning, review requests and verify completed training.",
    "/staff/training",
    "training course catalogue session cost request assign mandatory completion certificate verify",
    [
      "Open Training Records and choose the course, request, session or record area you need.",
      "Create or review the course details and scheduled sessions, including dates, provider and cost.",
      "Review employee requests or assign required learning to the relevant staff.",
      "After training, review completion evidence and certificates before marking the record verified.",
      "Use the employee’s training history to follow outstanding learning and completed courses.",
    ],
    "Course availability, a request, attendance and verified completion are separate stages.",
    [
      "Do not submit another open request for the same employee and course to bypass a pending review.",
      "Paid discretionary learning may need a reason even when a free course or mandatory assignment does not.",
    ],
    "training:manage_all",
  ),
  article(
    "hr-documents",
    "hr",
    "Documents & insurance",
    "Manage employee documents and expiry dates",
    "Keep the right document with the right person and follow renewals.",
    "/staff/files",
    "files document expiry passport visa work permit upload review version renewal employee",
    [
      "Open Employee Documents or the employee’s Documents section.",
      "Choose the correct employee and document type, then upload the file accepted by that form.",
      "Enter and review the relevant dates and information. Complete HR-owned visa and work-permit details yourself.",
      "Use Document Expiry to find records needing renewal and follow up with the responsible person.",
      "When replacing a document, use the supported replacement or new-version action so previous records are not confused with the current one.",
    ],
    "An uploaded document may still need review. Expiry information must match the actual document.",
    [
      "Do not upload a private employee document into a library shared with all staff.",
      "If there is no expiry, use the form’s appropriate option rather than inventing a date.",
    ],
    "document:manage_all",
  ),
  article(
    "hr-library",
    "hr",
    "Documents & insurance",
    "Publish SOPs, policies and company documents",
    "Give each document a clear name, audience and reliable current version.",
    "/staff/company-library",
    "sop policy ai question knowledge publish draft pdf company registration expiry version archive hr only",
    [
      "Open Policies & Documents and choose Upload document.",
      "Enter a clear document name, area and category. Choose All staff or HR only where that choice is available.",
      "Upload the original PDF, up to 10 MB, and complete the issue and expiry information requested. Use the no-expiry choice only when appropriate.",
      "Review the draft and any extracted policy text. Correct unreadable or inaccurate text before publishing for questions and answers.",
      "Publish the approved document. For a revision, use Upload new version; archive outdated documents through the available action.",
    ],
    "Company registration records and employee-facing SOPs have different audiences. Policy answers should refer to the reviewed published documents.",
    [
      "A draft upload is not publication. Check the status after saving.",
      "If an answer is unsupported or the document cannot be read, correct the source or ask HR to answer directly; do not treat an invented answer as policy.",
    ],
    "document:manage_all",
  ),
  article(
    "hr-insurance",
    "hr",
    "Documents & insurance",
    "Manage insurance cards and benefits documents",
    "Keep each employee’s card and the applicable benefits information together.",
    "/staff/employees",
    "insurance card table benefit coverage policy insurer validity dependants",
    [
      "Open the correct employee record and choose Documents.",
      "Use the upload action and choose Insurance Card or Insurance Table of Benefits as the document type.",
      "Upload the matching file and complete the details and validity dates requested. Insurance documents keep restricted employee-and-HR visibility.",
      "Review what the employee can see and replace outdated documents through the relevant update action.",
    ],
    "The documents help employees understand their cover; uploading them does not itself enrol a person with the insurer.",
    [
      "Check that the benefits table belongs to the correct plan and period. Keep another employee’s card private.",
    ],
    "employee:manage_all",
  ),
  article(
    "hr-finance",
    "hr",
    "Finance duties",
    "Prepare, approve and export a payroll period",
    "Collect the right information, resolve issues and obtain independent Finance approval.",
    "/staff/payroll/periods",
    "payroll salary finance accounts prepare approve different person export lock period overtime ledger",
    [
      "In your Finance role, open Finance → Payroll Inputs. On Payroll Periods, open the existing period or choose New Period. Check Period Name, Start Date, End Date, Cutoff Date and Payment Date, then Create Period.",
      "Open the period and choose Collect Inputs. Review Compiled Inputs and Exceptions. Ask HR to resolve incorrect employment, leave or timesheet information before continuing.",
      "If an authorised pay correction is needed, use Manual Adjustments and provide the required reason and evidence. Collect Inputs again after a correction so it is included.",
      "When the period is Prepared, a different authorised Finance person reviews it and chooses Approve Payroll. The preparer cannot approve their own prepared period.",
      "After approval, choose Lock Period, then Export CSV. Keep the exported file private and follow the company’s payment process outside this action.",
    ],
    "Payroll sign-off belongs to the Finance role. HR access alone does not grant payroll preparation or approval.",
    [
      "If only one Finance person is available, arrange an authorised independent reviewer; do not share an account.",
      "Changing attendance is not a shortcut for changing approved overtime or a locked pay period.",
      "If a locked or exported period is wrong, ask Super Admin to use Reopen for Correction with the required reason. Do not create a duplicate period or alter an old exported file as a substitute.",
      "Export CSV downloads the pay information. It does not transfer money to employees or upload their payslips.",
    ],
    "payroll:view",
  ),
  article(
    "hr-payslip",
    "hr",
    "Finance duties",
    "Upload or replace an employee payslip",
    "Issue the right document to the right employee and correct mistakes safely.",
    "/staff/payslips",
    "finance payslip salary upload individual replace incorrect reason current version",
    [
      "In your Finance role, open My Payslips and choose Manage employee payslips. The page changes to Employee Payslips with an upload form.",
      "Choose Employee and Pay month, then choose that employee’s PDF payslip, no larger than 10 MB. Open the file first to confirm the name and month are correct.",
      "Choose Upload & share. Check that the payslip appears in the list. It is immediately available to the employee, so this is not a draft upload.",
      "To fix an issued payslip, find the original in the list and choose Replace. Choose the corrected PDF, enter Reason for replacement and choose Replace & notify employee.",
      "Use History to inspect earlier versions. Use My payslips to return to your own personal documents.",
    ],
    "Employees can view their own issued payslips. HR should refer payslip corrections to Finance rather than changing payroll documents without access.",
    [
      "Never send a batch containing other employees’ payslips to one employee.",
      "A replaced file already downloaded by an employee will not change on their device; tell them to obtain the current version.",
    ],
    "payroll:prepare",
  ),
  article(
    "hr-reports",
    "hr",
    "Reports & administration",
    "Use reports and export the right selection",
    "Check dates and filters before sharing employee information.",
    "/staff/reports",
    "report export csv attendance leave year timesheet employee department location chart graph",
    [
      "Open Reports and choose the report relevant to your question.",
      "Select the employee, department, location and dates or leave year where available.",
      "Review the on-screen selection and any limits before exporting.",
      "Save the export securely and share it only with people authorised to see that information.",
    ],
    "A report reflects its selected period and filters. Different leave years should not be combined as if they were one allowance.",
    [
      "For one person, start from the employee record or use the employee filter.",
      "Exporting information does not give the recipient permission to redistribute it.",
    ],
    "employee:view_all",
  ),
  article(
    "hr-users",
    "hr",
    "Reports & administration",
    "Manage users and role access",
    "Give people the access needed for their responsibilities, while keeping their own employee workspace.",
    "/staff/users",
    "role permission finance accounts hr super admin it line manager access suspend active employee first",
    [
      "Open Users & Access and find the correct person.",
      "Review their linked employee record, current account status and assigned roles.",
      "Use the available role or status controls only for the access you are authorised to grant.",
      "Check the employee’s supervisor and ensure that anyone receiving approval tasks has the required approval access.",
      "Ask the person to select the correct role and verify the expected pages are available.",
    ],
    "A role gives access to defined responsibilities; it does not make the person cease to be an employee. Elevated administration changes can require Super Admin.",
    [
      "Do not give Super Admin merely so someone can approve payroll or view a colleague’s private file.",
      "Two people with the same role still have separate accounts and personal records. Assignment and self-approval checks still apply.",
    ],
    "system:users_manage",
  ),
  article(
    "hr-email",
    "hr",
    "Reports & administration",
    "Enable approval emails and reminders",
    "Use email alongside the in-app request and task lists.",
    "/staff/requests",
    "google email connect approval reminders missing clockout morning calendar notification mail delivery",
    [
      "On the HR dashboard, open HR setup and choose Enable emails or Connect calendar. Completed connections stay folded away. Office hours, leave policies and timesheet settings are also linked here where your role allows them.",
      "For connection details or to pause emails, choose Manage connections. You can also find Google Calendar & Meet in Requests & approvals → Organisation Tracker, or Interviews.",
      "Once email and calendar setup is complete, choose Hide from dashboard to remove the setup panel for your account on this browser. Emails and interviews keep working. To bring it back, open Organisation Tracker or Interviews and choose Show setup on dashboard under Google Calendar & Meet.",
      "Grant the separate email permission when enabling Approval emails & reminders; calendar permission alone is not enough.",
      "Review the connection and email status before relying on delivery.",
      "Open HR Settings → Reminder Settings to turn reminders on or off and change travel waiting hours, training expiry warning days, leave planning dates, offer warning hours and the next-morning missing-clock-out window. Select Save reminder settings. These settings are shared by the company and remain saved after sign-out. Document expiry warning days remain in Company Setup. Changes affect future reminders, not messages already sent; changing the leave reminder target never removes leave days.",
      "Continue monitoring Requests & approvals and My Tasks for the actual decisions and outstanding work.",
    ],
    "Emails depend on an active authorised connection and enabled reminder settings. A request can exist even if email delivery is unavailable.",
    [
      "Missing-clock-out emails are morning follow-ups for eligible unresolved records, not evening messages telling staff to go home.",
      "Enabling emails starts new notifications; it does not send every old notification. Sent means Google accepted the message, not that the recipient read it. Ask the administrator to review failed or uncertain messages before retrying.",
      "If HR revokes Google access or the connection needs attention, reconnect through the app. Do not paste account passwords into Help.",
    ],
    "employee:view_all",
  ),
  article(
    "hr-audit",
    "hr",
    "Reports & administration",
    "Ask for a change history or audit review",
    "Find who changed a sensitive record without sharing confidential history broadly.",
    "/staff/audit",
    "audit history export change reason denied sensitive high risk log",
    [
      "Start with the record’s own history when available.",
      "For a wider review, ask an authorised Super Admin to open Audit History.",
      "Choose the relevant date range, action or person, and read the event details in context.",
      "Check any displayed export limits before treating an exported list as the complete history.",
    ],
    "Audit events record actions and decisions; an event is not automatically proof that someone did something wrong.",
    [
      "The general colleague directory must not expose confidential employment-change reasons.",
      "Only share audit information with authorised reviewers.",
    ],
    "system:audit_view",
  ),
];

const setupTopics = [
  [
    "org",
    "Company details and working week",
    "company name timezone working week leave year",
    "Review the company name, contact details, local time zone and working-week choices shown. Check the leave-year setting where provided.",
    "Time-zone and working-week changes affect how dates and expected work are understood. Agree the change with HR before saving.",
  ],
  [
    "numbering",
    "Employee numbering",
    "number prefix employee id sequence",
    "Choose the numbering format and starting choices for the records shown. Check examples before saving.",
    "Do not change numbering simply to fix one person’s identity; review that employee’s record instead.",
  ],
  [
    "departments",
    "Add departments",
    "department team division add rename",
    "Search existing departments first. Add the approved department name or edit the relevant existing entry, then save.",
    "Adding a department does not automatically move employees into it. Update their employment records with the correct effective date.",
  ],
  [
    "locations",
    "Add work locations",
    "office country head office location site add",
    "Add the approved work location with the details requested and check whether it is active.",
    "A work location is not automatically a machine-attendance rule. HR must also review Head Office attendance setup.",
  ],
  [
    "positions",
    "Add positions and job titles",
    "position job title add role",
    "Check for an existing title before adding a new approved position. Save the position and confirm it is available in employee forms.",
    "A position title is not an access role. Changing a title does not grant approval permissions.",
  ],
  [
    "grades",
    "Set employment grades",
    "grade band level",
    "Add or amend the approved grade names and values requested by the form. Review existing use before making a grade inactive.",
    "Changing the list of grades does not itself authorise a salary change for an employee.",
  ],
  [
    "employmentTypes",
    "Add employment types",
    "employment type permanent contract temporary part time",
    "Add the approved employment type and check its active status. Keep names clear and consistent.",
    "Use employment records to assign the right type to a person; do not create a new type for a spelling variation.",
  ],
  [
    "workingTimes",
    "Set working times and breaks",
    "hours flexible lunch 1300 1400 830 1730 schedule",
    "Review the working-time entries, daily hours and break information available in the form. Check the agreed flexible-hours policy with HR.",
    "A reference start time is not permission to mark every earlier or later arrival as wrong. Attendance and timesheet rules must agree.",
  ],
  [
    "publicHolidays",
    "Maintain public holidays",
    "holiday calendar non working day",
    "Add the holiday name and correct date or dates. Review existing entries to avoid counting the same holiday twice.",
    "Check the year and applicable company arrangements before updating expected working days.",
  ],
  [
    "leavePolicies",
    "Review company leave rules",
    "leave settings allowance year eligibility nationality",
    "Review the leave policy controls with HR, including allowances and conditions. HR can use Leave Policies for its permitted changes.",
    "Confirm the approved policy before changing entitlement or eligibility. Do not assume every employee qualifies for every leave type.",
  ],
  [
    "interviewTemplates",
    "Set interview scorecards",
    "interview template score criteria panel questions",
    "Create or update the interview template with the questions and assessment criteria the panel should use.",
    "Keep questions relevant to the role and ensure interviewers understand the scoring before using the template.",
  ],
  [
    "onboardingTemplates",
    "Set joining checklists",
    "onboarding template tasks owner due date",
    "Add the standard joining tasks with clear descriptions, responsible roles and timing choices available in the form.",
    "A template is a starting checklist. Review each new employee’s actual case and owners.",
  ],
  [
    "offboardingTemplates",
    "Set leaving checklists",
    "offboarding template clearances return equipment",
    "Include the required handover, equipment, Finance and access-removal tasks with clear responsibility.",
    "Changing a template does not confirm an existing case’s clearances or complete the case.",
  ],
  [
    "performanceTemplates",
    "Set objectives and appraisal templates",
    "performance template objective goal review criteria",
    "Define the objectives and review criteria offered for a performance cycle. Use wording employees and managers can understand.",
    "Check the template before opening a cycle; changing a template is not the same as agreeing an individual’s objectives.",
  ],
  [
    "projects",
    "Maintain projects and assignments",
    "project add assignment active",
    "Add or review a project, its active status and the assignments offered by the page. Check the project name with the responsible team.",
    "Do not use a duplicate project to get around an inactive or closed project without authorisation.",
  ],
  [
    "costCentres",
    "Maintain cost centres",
    "cost centre finance code",
    "Add the Finance-approved cost centre name and code. Review existing entries before saving a new one.",
    "Agree code changes with Finance before employees use them in work records.",
  ],
  [
    "activityCodes",
    "Maintain timesheet activity choices",
    "activity code timesheet task category",
    "Add clear activity names or codes that staff can select when recording work. Keep obsolete choices separate from current ones.",
    "Do not make staff guess between near-identical activity names.",
  ],
  [
    "currencies",
    "Maintain currency choices",
    "currency payment travel expenses",
    "Review the supported currency entries and add only the approved choices needed by the company.",
    "A currency choice does not itself set or guarantee an exchange rate or reimbursement amount.",
  ],
  [
    "data",
    "Protect records and plan recovery",
    "backup recovery retention delete restore data management",
    "Ask the authorised administrator to review backup status, recovery arrangements and retention choices in Data management.",
    "Recovery or removal of records can affect the whole company. Agree the scope, check the confirmation carefully and never test it on live employee records.",
  ],
] as const;

const setupLabels = {
  org: "Company information",
  numbering: "Employee numbering",
  departments: "Departments",
  locations: "Locations",
  positions: "Positions",
  grades: "Grades",
  employmentTypes: "Employment types",
  workingTimes: "Working times",
  publicHolidays: "Public holidays",
  leavePolicies: "Leave policies",
  interviewTemplates: "Interview scorecards",
  onboardingTemplates: "Onboarding checklists",
  offboardingTemplates: "Offboarding checklists",
  performanceTemplates: "Performance templates",
  projects: "Projects",
  costCentres: "Cost centres",
  activityCodes: "Activity codes",
  currencies: "Currencies",
  data: "Data management",
};

export const setupGuide = setupTopics.map(([section, title, keywords, step, caution]) =>
  article(
    `setup-${section.toLowerCase()}`,
    "hr",
    "Company setup",
    title,
    "Company-wide setup: arrange this with an authorised Super Admin.",
    `/staff/settings?section=${section}`,
    keywords,
    [
      "Agree the intended change with the responsible HR or Finance person before changing a company-wide choice.",
      `An authorised Super Admin opens HR Settings → Company Setup → ${setupLabels[section]}.`,
      step,
      "Save and reopen the relevant form to check the new choice. Review any affected employee assignments separately.",
    ],
    "The saved setup is shared by the relevant parts of the app. The HR guide explains the task, but it does not grant extra access.",
    [
      caution,
      "If HR cannot open Company Setup, ask Super Admin to make this change. Do not use another person’s account.",
    ],
    "system:settings_manage",
  ),
);
